# Generated by Django 4.2.4 on 2023-09-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateField(null=True)),
                ('app_name', models.TimeField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('type', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
