# Generated by Django 4.2.4 on 2023-09-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_passwords_time_alter_passwords_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='app_name',
            field=models.TextField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='password',
            field=models.TextField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='type',
            field=models.TextField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='username',
            field=models.TextField(verbose_name=10),
        ),
    ]
