# Generated by Django 4.2.4 on 2023-09-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0004_alter_passwords_app_name_alter_passwords_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='app_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
