# Generated by Django 4.2.4 on 2023-09-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0005_alter_passwords_app_name_alter_passwords_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='passwords',
            new_name='Password',
        ),
    ]
